### ISSUE TITLE
Should we make this public?

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/comet_sw#1]
Hi @wcparker ,

I just noticed that this project is private (which is the default settings for new projects). Can we make this public, given that our COMET FW is already public, it makes sense to also make the tool required to sideload the firmware also public?

BTW, the COMET firmware is called `comet_fw` (all lower case), can we also change the name of the project to `comet_sw` to satisfy my OCD?

**Comment by wcparker** [comment]
Sure to both.  However I don't think what you say is correct that this is a tool to sideload COMET firmware.  This is the software to operate the COMET.  It does so by communicating with the firmware, but the firmware already has to be loaded.

**Comment by yipengsun** [comment]
Done!
